# Generated by Django 4.2.1 on 2024-04-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the grade level', max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(help_text='The order in which the grade level appears')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the subject, e.g., MATH101', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Name of the subject, e.g., Mathematics', max_length=100)),
                ('description', models.TextField(blank=True, help_text='A brief description of the subject')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section Name', max_length=50, unique=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section', to='academic.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(help_text='The start year of the school year, e.g., 2024')),
                ('end_year', models.PositiveSmallIntegerField(help_text='The end year of the school year, e.g., 2025')),
                ('is_current', models.BooleanField(default=False, help_text='Indicates if this is the current school year')),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Curriculum', max_length=100)),
                ('grade_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='academic.gradelevel')),
            ],
            options={
                'verbose_name_plural': 'curricula',
            },
        ),
    ]
