# Generated by Django 4.2.1 on 2024-04-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_curriculum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name_plural': 'curricula'},
        ),
    ]
