# Generated by Django 4.2.1 on 2024-03-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='birth_place',
            field=models.CharField(default='Place', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated')], max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='country_of_birth',
            field=models.CharField(default='Country', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(default='2000-05-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mobile_number',
            field=models.CharField(default='12345678901', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(default='Pinoy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='personal_email',
            field=models.EmailField(default='jm@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(default='Christian', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text="Student's account status", max_length=8),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='student.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('barangay', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.personalinfo')),
            ],
        ),
    ]
