# Generated by Django 4.2.1 on 2024-03-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_personalinfo_birth_place_personalinfo_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='student.personalinfo'),
        ),
    ]
