# Generated by Django 4.2.1 on 2024-03-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_contact_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('birth_date', models.DateField()),
                ('country_of_birth', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated')], max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('religion', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text="Student's account status", max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='personal_info',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='personal_info',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.AddField(
            model_name='address',
            name='student',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='student',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='student.student'),
            preserve_default=False,
        ),
    ]
