# Generated by Django 4.2.1 on 2024-03-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_remove_address_personal_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
