# Generated by Django 4.2.1 on 2024-03-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolyear',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='academic.gradelevel'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.schoolyear'),
        ),
        migrations.DeleteModel(
            name='GradeLevel',
        ),
        migrations.DeleteModel(
            name='SchoolYear',
        ),
    ]
